# Generated by Django 2.1.2 on 2018-10-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
