# Generated by Django 2.1.2 on 2018-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengerAPI', '0002_auto_20181020_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
