# Generated by Django 2.1.2 on 2018-10-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengerAPI', '0003_auto_20181021_0044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Passenger',
        ),
    ]
