# Generated by Django 2.1.2 on 2018-10-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengerAPI', '0006_driverlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='driver_id',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverLocation',
        ),
    ]
