# Generated by Django 2.1.2 on 2018-10-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverAPI', '0002_driverrideshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverrideshistory',
            name='distance_travelled',
        ),
    ]
