# Generated by Django 2.1.2 on 2018-10-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverAPI', '0004_driverrideshistory_car_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverrideshistory',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='driverrideshistory',
            name='passenger_id',
        ),
        migrations.DeleteModel(
            name='DriverRidesHistory',
        ),
    ]
