# Generated by Django 2.1.2 on 2018-10-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverAPI', '0005_auto_20181023_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='driver_id',
        ),
        migrations.DeleteModel(
            name='DriverLocation',
        ),
    ]
