# Generated by Django 2.1.2 on 2018-10-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengerAPI', '0010_auto_20181023_1709'),
        ('driverAPI', '0006_auto_20181023_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverAPI.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverRidesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_address', models.TextField()),
                ('destination_address', models.TextField()),
                ('booked_time', models.DateTimeField(auto_now_add=True)),
                ('car_no', models.CharField(max_length=80, unique=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverAPI.Driver')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengerAPI.Passenger')),
            ],
        ),
    ]
