# Generated by Django 2.1.2 on 2018-10-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverAPI', '0007_driverlocation_driverrideshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrideshistory',
            name='passenger_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
